trigger:
- none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'
  solution: '**/*.sln'
  projectPath: 'src/MaH.IOC/MaH.IOC.csproj'  # Update with the path to your .csproj file
  outputDir: '$(Build.ArtifactStagingDirectory)/nuget'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(projectPath)'
    msbuildArgs: '/p:Configuration=$(buildConfiguration)'
    configuration: '$(buildConfiguration)'

- script: |
    curl -L -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    .\nuget.exe pack $(projectPath) -OutputDirectory $(outputDir) -Properties Configuration=$(buildConfiguration)
  displayName: 'Pack NuGet Package'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(outputDir)'
    ArtifactName: 'nuget'
    publishLocation: 'Container'